// Generated by CoffeeScript 1.6.2
(function() {
  var Thumbnail;

  window.Gallery = (function() {
    Gallery.prototype.displays = [];

    Gallery.prototype.thumbnails = [];

    Gallery.prototype.currentIndex = -1;

    Gallery.prototype.onReachEnd = null;

    Gallery.prototype.onReachBeginning = null;

    function Gallery(thubmailsListing, displayListing, thumbnailsElement, displayElement, thumbsDisplayed) {
      this.thubmailsListing = thubmailsListing;
      this.displayListing = displayListing;
      this.thumbnailsElement = thumbnailsElement;
      this.displayElement = displayElement;
      this.thumbsDisplayed = thumbsDisplayed != null ? thumbsDisplayed : 3;
      this._createThumbnails();
      this._createDisplay();
    }

    Gallery.prototype._createThumbnails = function() {
      var _this = this;

      $.each(this.thubmailsListing, function(index, url) {
        var clickHandler, thumbnail;

        clickHandler = $.proxy(_this.display, _this, index);
        thumbnail = new Thumbnail(url, clickHandler);
        thumbnail.element.appendTo(_this.thumbnailsElement);
        _this.thumbnails.push(thumbnail);
      });
    };

    Gallery.prototype._createDisplay = function() {
      var _this = this;

      $.each(this.displayListing, function(index, url) {
        var img, li;

        li = $('<li></li>');
        img = $('<img>').attr('src', url);
        img.appendTo(li);
        li.appendTo(_this.displayElement);
        _this.displays.push(li);
      });
    };

    Gallery.prototype._getPositionAt = function(index, elementList) {
      var height;

      height = 0;
      $.each(elementList, function(i, item) {
        var element;

        element = item.element ? item.element : item;
        if (i < index) {
          height += element.height();
        }
      });
      return height;
    };

    Gallery.prototype.previous = function() {
      this.display(Math.max(this.currentIndex - 1, 0));
    };

    Gallery.prototype.next = function() {
      this.display(Math.min(this.currentIndex + 1, this.thumbnails.length - 1));
    };

    Gallery.prototype.display = function(index) {
      if (index === this.currentIndex) {
        return;
      }
      this.thumbnailsElement.animate({
        scrollTop: "" + (Math.max(this._getPositionAt(index - this.thumbsDisplayed + 1, this.thumbnails), 0)) + "px"
      });
      this.displayElement.animate({
        scrollTop: "" + (this._getPositionAt(index, this.displays)) + "px"
      });
      if (this.currentIndex >= 0) {
        this.thumbnails[this.currentIndex].setSelected(false);
      }
      this.thumbnails[index].setSelected(true);
      this.currentIndex = index;
      if (this.onReachBeginning !== null) {
        this.onReachBeginning(index === 0);
      }
      if (this.onReachEnd !== null) {
        this.onReachEnd(index === this.thumbnails.length - 1);
      }
    };

    return Gallery;

  })();

  Thumbnail = (function() {
    Thumbnail.prototype.element = null;

    function Thumbnail(thumbUrl, clickHandler) {
      var img, li;

      this.thumbUrl = thumbUrl;
      li = $('<li></li>');
      img = $('<img>').attr('src', this.thumbUrl);
      img.appendTo(li);
      li.click(clickHandler);
      this.element = li;
    }

    Thumbnail.prototype.setSelected = function(value) {
      if (value) {
        this.element.addClass('selected');
      } else {
        this.element.removeClass('selected');
      }
    };

    return Thumbnail;

  })();

}).call(this);
